# Generated by Django 2.1.1 on 2018-09-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planned_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planned_trip', to='trip_buddy.User'),
            preserve_default=False,
        ),
    ]
